services:
  traefik:
    image: "traefik:v3.6.14"
    container_name: "traefik"
    restart: always
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--metrics.prometheus=true"
    environment:
      - TZ=Europe/Brussels
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.auth.basicauth.users=${TFK_USER}"
      - "traefik.http.routers.api.rule=Host(`traefik.${DOMAIN}`)" # Replace with your dashboard domain
      - "traefik.http.routers.api.entrypoints=websecure" # Use HTTPS for the dashboard
      #- "traefik.http.routers.api.entrypoints=web" # debug
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=myresolver" # Link to the ACME resolver
      - "traefik.http.routers.api.middlewares=auth" # Apply basic auth middleware
    networks:
      - external

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
    - ${DATA_DIR}/vw-data:/data
    environment:
    #- DATABASE_URL=${VAULT_DB}
    - SIGNUPS_ALLOWED=false
    - DOMAIN=https://vault.${DOMAIN}
    - ADMIN_TOKEN=${VW_TOKEN}
    - TZ=Europe/Brussels
    - LOG_FILE=/data/logs.log
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.vaultwarden.rule=Host(`vault.${DOMAIN}`)"
    - "traefik.http.routers.vaultwarden.entrypoints=websecure"
    - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
    - "traefik.http.routers.vaultwarden.tls=true"
    - "traefik.http.routers.vaultwarden.tls.certresolver=myresolver"
    - "traefik.http.middlewares.vaultwarden.headers.stsseconds=31536000"
    - "traefik.http.middlewares.vaultwarden.headers.stsincludesubdomains=true"
    - "traefik.http.middlewares.vaultwarden.headers.stspreload=true"
    - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - external
      
  fail2ban:
    image: lscr.io/linuxserver/fail2ban:latest
    container_name: fail2ban
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TZ=Europe/Brussels
      - PUID=1000
      - PGID=1000
      - F2B_DB_PURGE_AGE=14d
    volumes:
      - ${DATA_DIR}/fail2ban/config:/config
      - ${DATA_DIR}/vw-data:/remotelogs/vaultwarden:ro
      - ${DATA_DIR}/mealie-data/mealie.log:/remotelogs/mealie.log:ro  
      - ${LOGS_DIR}/var/log:/var/log:ro
    restart: unless-stopped

  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.12.0 # 
    container_name: mealie
    restart: unless-stopped
    ports:
        - "9925:9000" # 
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - ${DATA_DIR}/mealie-data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: Europe/Brussels
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: https://recipes.${DOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mealie.rule=Host(`recipes.${DOMAIN}`)"
      - "traefik.http.routers.mealie.entrypoints=websecure"
      - "traefik.http.routers.mealie.tls=true"
      - "traefik.http.routers.mealie.tls.certresolver=myresolver"
    networks:
      - external

  glance:
    image: glanceapp/glance
    container_name: glance
    restart: unless-stopped
    environment:
      - GLANCE_SECRET=${GLANCE_SECRET}
      - GLANCE_NICO_PSWD=${GLANCE_NICO_PSWD}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DATA_DIR}/glance/config:/app/config
      - ${DATA_DIR}/glance/assets:/app/assets
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glance.rule=Host(`feed.${DOMAIN}`)"
      - "traefik.http.routers.glance.entrypoints=websecure"
      - "traefik.http.routers.glance.tls=true"
      - "traefik.http.routers.glance.tls.certresolver=myresolver"
      - "traefik.http.services.glance.loadbalancer.server.port=8080"
    networks:
      - external

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    user: "0"
    volumes:
      - ${DATA_DIR}/grafana/data:/var/lib/grafana
      - ${DATA_DIR}/grafana/conf:/etc/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN}`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    networks:
      - external
       
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - "${DATA_DIR}/prometheus/:/etc/prometheus"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.size=256MB'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.${DOMAIN}`)"
      - "traefik.http.routers.prometheus.service=prometheus"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
    networks:
      - external
      - internal

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  db-cheatsheet:
    image: nicojmn/db-cheatsheet:latest
    container_name: db-cheatsheet
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cheatsheet.rule=Host(`databases.${DOMAIN}`)"
      - "traefik.http.routers.cheatsheet.entrypoints=websecure"
      - "traefik.http.routers.cheatsheet.tls=true"
      - "traefik.http.routers.cheatsheet.tls.certresolver=myresolver"
      - "traefik.http.services.cheatsheet.loadbalancer.server.port=80"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - external

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    command: --interval 900 --label-enable --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${DATA_DIR}/st-sync:/var/syncthing
      - /home/nicolas/.config/helix:/var/syncthing/helix:rw
      - /tmp/test:/mnt/test-user
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sync.rule=Host(`sync.${DOMAIN}`)"
      - "traefik.http.routers.sync.entrypoints=websecure"
      - "traefik.http.routers.sync.tls=true"
      - "traefik.http.routers.sync.tls.certresolver=myresolver"
      - "traefik.http.services.sync.loadbalancer.server.port=22000"
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3

  renew-ip:
    image: nicojmn/govh-renew-ip:latest
    container_name: renew-ip
    environment:
      - OVH_ENDPOINT=${OVH_ENDPOINT}
      - OVH_APP_KEY=${OVH_APP_KEY}
      - OVH_APP_SECRET=${OVH_APP_SECRET}
      - OVH_CONSUMER_KEY=${OVH_CONSUMER_KEY}
      - DOMAIN=${DOMAIN}
      - TIME_INTERVAL=${TIME_INTERVAL}
    restart: unless-stopped
    networks:
      - internal6

  forgejo:
    image: codeberg.org/forgejo/forgejo:15
    container_name: forgejo
    depends_on:
      - forgejo_db
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=forgejo_db:5432
      - FORGEJO__database__NAME=forgejo
      - FORGEJO__database__USER=forgejo
      - FORGEJO__database__PASSWD=${FORGEJO_DB_PSWD}
    restart: unless-stopped
    networks:
      - external
    volumes:
      - ${DATA_DIR}/forgejo:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '3000:3000'
      - '222:22'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.forgejo.rule=Host(`git.${DOMAIN}`)"
      - "traefik.http.routers.forgejo.entrypoints=websecure"
      - "traefik.http.routers.forgejo.tls=true"
      - "traefik.http.routers.forgejo.tls.certresolver=myresolver"
      - "traefik.http.services.forgejo.loadbalancer.server.port=3000"

  forgejo_db:
    image: postgres:14
    container_name: forgejo_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=forgejo
      - POSTGRES_PASSWORD=${FORGEJO_DB_PSWD}
      - POSTGRES_DB=forgejo
    networks:
      - external
    volumes:
      - ${DATA_DIR}/forgejo-db:/var/lib/postgresql/data  
      
  forgejo-runner:
    image: data.forgejo.org/forgejo/runner:12
    container_name: forgejo-runner
    user: root
    command: forgejo-runner daemon --config /data/runner-config.yaml
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ${DATA_DIR}/forgejo-runner:/data
      - ${DATA_DIR}/forgejo-runner/config.yaml:/data/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  data:
  vw-data:
  focalboard:
  mealie-data:

networks:
  external:
   # external: true
  internal:
  internal6:
    driver: bridge
    enable_ipv6: true
